version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "streams-dynamodb-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18fdxjjduqr65"
s3_prefix = "streams-dynamodb-sam"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
